# カウントダウンの秒数
countdown: 20

# 入札の最低価格
bid-min-price-multi: 1.05 # 元値への倍率
bid-min-price-add: 100 # 元値への加算値

# ルール説明の定型文
rule:
  - "&d&l～運営オークションのルール～"
  - "&aさ&bん&cぷ&dる&eぷ&1る&2ぷ&3る"
  - "同じように行を増やせば説明を増やせるよ"
  - "でもTwitter民は3行までの文章しか読めないから配慮してあげてね"
